syntax = "proto3";

package penumbra.core.component.tokenfactory.v1alpha;

import "penumbra/core/asset/v1/asset.proto";

// TokenFactoryParameters defines the parameters for the tokenfactory component.
message TokenFactoryParameters {
    bool is_enabled = 1;
}

// GenesisContent defines the genesis state for the tokenfactory component.
message GenesisContent {
  TokenFactoryParameters token_factory_params = 1;
}

// ActionTokenFactoryCreate defines the action for creating a new token factory.
message ActionTokenFactoryCreate {
  // Add fields as needed
} 

// ActionTokenBurn defines the action for burning a token.
message ActionTokenBurn {
  // Add fields as needed
}

// TokenBurn defines the action for burning a token.
message TokenBurn {
  string token_id = 1;
  uint64 seq = 2;
  uint64 amount = 3;
}